### ISSUE TITLE
PHP failure to fetch PPA information

### ISSUE THREAD

**Issue by lgrimm** [netsensei/ansible-collectiveaccess#2]
Mac OS 10.12.6
VirtualBox v 5.1.3 (v5.2 unsupported)
Vagrant v 2.0.0
Ansible v 2.4

VM builds and "Welcome to nginx!" page loads, but ansible playbook reports:
TASK [php : Add ppa Repository] ************************************************
fatal: [192.168.2.145]: FAILED! => {"changed": false, "failed": true, "msg": "failed to fetch PPA information, error was: HTTP Error 404: Not Found"}

I tried editing the all.xml to:
php:
    install: '1'
    ppa: php5-5.6
    packages: [php5.6-cli, php5.6-intl, php5.6-mcrypt, php5.6-mysql, php5.6-curl, php5.6-gd] 

but no luck.

**Comment by netsensei** [comment]
Okay. PHP is not installed from the ubuntu repository, but from a separate repository which does contain more actual version of PHP (5.6, 7.x). The way this repo is structured / configured has changed:

https://launchpad.net/~ondrej/+archive/ubuntu/php
https://stackoverflow.com/questions/40567133/cannot-add-ppa-ppaondrej-php5-5-6

I changed the PHP role accordingly. This should work now.

**Comment by lgrimm** [comment]
Thanks! I was following several threads that hinted at that. I have had success now. Cheers!!
